consoleIngress:
  annotations:
    cert-manager.io/cluster-issuer: cluster-ca
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  enabled: true
  hosts:
  - minio.cluster.lan
  ingressClassName: nginx
  path: /
  pathType: Prefix
  tls:
  - hosts:
    - minio.cluster.lan
    secretName: minio-console-tls
existingSecret: minio-credentials
ingress:
  annotations:
    cert-manager.io/cluster-issuer: cluster-ca
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  enabled: true
  hosts:
  - minio-api.cluster.lan
  ingressClassName: nginx
  path: /
  pathType: Prefix
  tls:
  - hosts:
    - minio-api.cluster.lan
    secretName: minio-api-tls
mode: standalone
persistence:
  enabled: true
  size: 4Gi
  storageClass: longhorn
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi
